### PR TITLE
📦️ Toon shader

### LINKED ISSUE #207: 🎨Add toon shader

### PR DESCRIPTION
**Pull request by davey2206**
## Content

Added toon shader pro 2 and updated materials to use it

image

### Added
Added Toon Shader Pro 2 in `Assets/Plugins/JMO Assets`

### Updated
All materials in `Assets/Art/PolygonAdventure` updated to use toon shader.
All materials in `Assets/Art/PolygonVikings` updated to use toon shader.
All materials in `Assets/Art/PolygonKnights` updated to use toon shader.
`Assets/Settings/URP-Performant-Renderer.asset` was updated to work with toon shader outlines
`Assets/Settings/URP-HighFidelity-Renderer.asset` was updated to work with toon shader outlines
`Assets/Settings/URP-Balanced-Renderer.asset` was updated to work with toon shader outlines

Closes #207

### CODE REVIEW

**Review by NathanThus — CHANGES_REQUESTED** [review]
image

No? You can start by removing the demo files, which we absolutely do **NOT** need.
Alternatively, please label why you added them 😜

**Review by NathanThus — CHANGES_REQUESTED** [review]
Do we need the `Fonts`, `Legacy` and `Examples` as well?
See my previous comment about labeling them 😉

**Comment by davey2206** [comment]
No idea if I can remove them I did not create the plugin you know. and cant label them when I don't know what they do + its a real waste of time to label 300+ files. I know you want to do things professionally but its still just a school project for now with very limited time to develop it.

**Comment by NathanThus** [comment]
image

Well, either way, apparently you're missing a file.

**Comment by NathanThus** [comment]
> No idea if I can remove them I did not create the plugin you know. and cant label them when I don't know what they do + its a real waste of time to label 300+ files. I know you want to do things professionally but its still just a school project for now with very limited time to develop it.

I am aware, and I was being sarcastic regarding the labeling, as it is **beyond** unreasonable to ask that.
And as far as the files are concerned, I simply want people to take a genuine look if something is absolutely necessary, as it avoids cleanup later down the line. Font's most likely aren't, as unity has a fallback font to rely upon.

I'll do a bit of cleanup, see what I can reduce. Hopefully you understand my reasoning.

**Comment by NathanThus** [comment]
@davey2206 Fix the missing file, and I'll approve it. We're already down to 391 from 1176, so I'll take that improvement.

**Comment by davey2206** [comment]
The shader generator is not needed for our game. We only use the default Hybrid 2 shader to get the look and outline. if we want more advanced options for our shader we can add this in the future.

**Review by NathanThus — APPROVED** [review]
Looks good, and we removed everything we did not need (for the most part).

**Pull request merged**
