### PR TITLE
🐛 Dash direction without input

### PR DESCRIPTION
**Pull request by Timsel1**
## Content

Player used to always dash toward world direction forward when no input was detected, no more, introducing "this bugfix". The player now dashes in the direction the character is looking when no input is detected. DAAAAAAAAAMN that's sick!

### Updated
`Assets/Scripts/Player/Movement/PlayerController.cs` : Was updated. Added a check for dashing without input.

## Testing

The feature / Bugfix can be testing by following these steps:

Davey has seen it, ask him please.

### CODE REVIEW

**Review by NathanThus — APPROVED** [review]
Looks good to me, but I'll wait for @AoSkye29

**Review by NathanThus — CHANGES_REQUESTED** [review]
Revert!

**Review by AoSkye29 — APPROVED** [review]
Ich werde diese Änderungen genehmigen, aber bitte halten Sie einen ordnungsgemäßen Test bereit, bevor Sie mich dazu zwingen, Davey um eine nochmalige Überprüfung zu bitten.

**Review by NathanThus — APPROVED** [review]
:)

**Pull request merged**
